blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions
    url: https://github.com/orgs/rtbnext/discussions
    about: Ask questions or start a discussion.

  - name: RTBNext Status
    url: https://status.rtbnext.de
    about: Check the current operational status of RTBNext services.
